In [1]:
import requests
import json
import pandas as pd
import datetime
from dateutil.relativedelta import *

In [2]:
with open('key_info.json') as json_file:
    json_data = json.load(json_file)
    key = json_data['key']

In [3]:
numdays = 120

In [4]:
base = datetime.datetime(2020, 9, 1)
date_list = [(base + relativedelta(months=-x)).strftime('%Y%m%d') for x in range(numdays)]

In [5]:
data_list = []
for date in date_list:
    url = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key='+key+'&targetDt='+date
    data = json.loads(requests.get(url).text)['boxOfficeResult']['dailyBoxOfficeList']
    movie_data = pd.DataFrame(data)
    movie_data['searchdate'] = date
    data_list.append(movie_data)

In [6]:
all_df = pd.concat(data_list).reset_index(drop=True)
all_df.head()

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,searchdate
0,1,1,0,OLD,20201122,테넷,2020-08-26,405736600,73.3,-72593680,-15.2,6902129920,46440,-7567,-14,760852,2018,6303,20200901
1,2,2,0,OLD,20197922,다만 악에서 구하소서,2020-08-05,71605890,12.9,-14860840,-17.2,37840926140,8671,-1981,-18.6,4269455,656,1696,20200901
2,3,3,0,OLD,20199883,오케이 마담,2020-08-12,30534760,5.5,-7155690,-19,10820555960,3774,-874,-18.8,1208973,531,961,20200901
3,4,4,0,OLD,20202281,극장판 짱구는 못말려: 신혼여행 허리케인~ 사라진 아빠!,2020-08-20,14227100,2.6,-1411320,-9,797335940,1862,-133,-6.7,98099,323,424,20200901
4,5,5,6,OLD,20010238,메멘토,2001-08-24,4249000,0.8,1890500,80.2,334180800,420,125,42.4,45052,32,49,20200901

In [7]:
all_df.to_csv('movie_data.csv', index=False)